_.set  # unused method (ch5mpy/attributes.py:74)
_.rename  # unused method (ch5mpy/dict.py:179)
_.is_chunked  # unused property (ch5mpy/h5array/array.py:247)
_.write  # unused method (ch5mpy/list.py:90)
_.to_dict  # unused method (ch5mpy/list.py:124)
_.has_write_intent  # unused method (ch5mpy/names.py:21)
_.attributes  # unused property (ch5mpy/objects/object.py:61)
h5dict  # unused variable (ch5mpy/options.py:6)
