_.set  # unused method (ch5mpy/attributes.py:64)
_.is_chunked  # unused property (ch5mpy/h5array/array.py:248)
_.write  # unused method (ch5mpy/list.py:90)
_.to_dict  # unused method (ch5mpy/list.py:124)
WRITE_TRUNCATE  # unused variable (ch5mpy/names.py:17)
WRITE  # unused variable (ch5mpy/names.py:18)
_.attributes  # unused property (ch5mpy/objects/object.py:53)
