_.is_chunked  # unused property (ch5mpy/h5array/array.py:249)
_.contract  # unused method (ch5mpy/h5array/array.py:303)
_.p  # unused method (ch5mpy/h5array/creation_routines.py:59)
WRITE_TRUNCATE  # unused variable (ch5mpy/names.py:17)
WRITE  # unused variable (ch5mpy/names.py:18)
READ_WRITE_CREATE  # unused variable (ch5mpy/names.py:19)
_.write  # unused method (ch5mpy/objects/list.py:89)
_.to_dict  # unused method (ch5mpy/objects/list.py:123)
